### ISSUE TITLE
Wot the eck is gastby

### ISSUE THREAD

**Issue by yjsoon** [swiftinsg/swiftinsg.github.io#16]
![CleanShot 2022-06-18 at 09 56 27](https://user-images.githubusercontent.com/126824/174418095-d000e5ba-c080-4c5c-84c2-8d6dfe4d2966.png)

**Comment by yjsoon** [comment]
This is in the README btw

**Comment by yjsoon** [comment]
@jamesrchen

**Comment by jamesrchen** [comment]
That line of instruction wasn't even consistent in the first place. Fixed in 388065a108b29008c98a57ddd16a37947445a805
